services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5433:5432"
    networks:
      - pg-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network
    restart: always

networks:
  pg-network:

volumes:
  postgresql:
  pgadmin: