services:
  postgres:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5433:5432"
    networks:
      - postgresql
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgresql
    restart: always

networks:
  postgresql:
    driver: bridge

volumes:
  postgresql:
  pgadmin: